apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sentinel-stack
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: sentinel
  sources:
    - repoURL: https://github.com/ViniciusPilan/k8s-cluster.git
      targetRevision: main
      ref: repository
    # <----------------------- Operator ------------------------>
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack 
      targetRevision: 58.7.2
      helm:
        releaseName: prometheus-operator
        valueFiles:
        - $repository/sentinel-stack/commom-values.yaml
        - $repository/sentinel-stack/prometheus/operator-values.yaml
    # <----------------------- Prometheus ---------------------->
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack 
      targetRevision: 58.7.2
      helm:
        releaseName: prometheus
        valueFiles:
        - $repository/sentinel-stack/commom-values.yaml
        - $repository/sentinel-stack/prometheus/prometheus-values.yaml
        - $repository/sentinel-stack/prometheus/core-monitors-values.yaml
    # <----------------------- Node exporter ---------------------->
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack 
      targetRevision: 58.7.2
      helm:
        releaseName: node-exporter
        valueFiles:
        - $repository/sentinel-stack/commom-values.yaml
        - $repository/sentinel-stack/prometheus/node-exporter/node-exporter-values.yaml
    # <----------------------- Grafana ------------------------->
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack 
      targetRevision: 58.7.2
      helm:
        releaseName: grafana
        valueFiles:
        - $repository/sentinel-stack/commom-values.yaml
        - $repository/sentinel-stack/grafana/grafana-values.yaml
    # <----------------------- Mimir ------------------------->
    - repoURL: https://grafana.github.io/helm-charts
      chart: mimir-distributed
      targetRevision: 5.3.0 
      helm:
        releaseName: mimir
        valueFiles:
        - $repository/sentinel-stack/mimir/mimir-values.yaml
    # <----------------------- Loki ------------------------->
    - repoURL: https://grafana.github.io/helm-charts
      chart: loki-stack
      targetRevision: 2.10.2 
      helm:
        releaseName: loki
        valueFiles:
        - $repository/sentinel-stack/loki/loki-values.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
