apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sentinel-stack
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: sentinel
  sources:
    - repoURL: https://github.com/ViniciusPilan/k8s-cluster.git
      targetRevision: main
      ref: repository
    # <----------------------- Operator ----------------------->
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack 
      targetRevision: 58.7.2
      helm:
        releaseName: prometheus-operator
        valueFiles:
        - $repository/sentinel-stack/commom-values.yaml
        - $repository/sentinel-stack/operator-values.yaml
    # <----------------------- Prometheus ----------------------->
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack 
      targetRevision: 58.7.2
      helm:
        releaseName: prometheus
        valueFiles:
        - $repository/sentinel-stack/commom-values.yaml
        - $repository/sentinel-stack/prometheus-values.yaml
    # <----------------------- Grafana ----------------------->
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack 
      targetRevision: 58.7.2
      helm:
        releaseName: grafana
        valueFiles:
        - $repository/sentinel-stack/commom-values.yaml
        - $repository/sentinel-stack/grafana-values.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
