apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: mimir
    grafana_datasource: "1"
  name: mimir-datasource
  namespace: sentinel
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Mimir
      type: prometheus
      uid: mimir
      url: http://mimir-nginx.sentinel.svc/prometheus
      access: proxy
      isDefault: true
      jsonData:
        httpMethod: POST
        timeInterval: 30s
