apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: grafana
    grafana_datasource: "1"
    stack: sentinel
  name: prometheus-datasource-test
  namespace: sentinel
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus-test
      type: prometheus
      uid: prometheus-test
      url: http://sentinel-prometheus.sentinel:9090/
      access: proxy
      isDefault: true
      jsonData:
        httpMethod: POST
        timeInterval: 30s

