apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: sentinel-prometheus
    prometheus: sentinel
    release: prometheus
    stack: sentinel
  name: sentinel-prometheus
  namespace: sentinel
spec:
  endpoints:
  - path: /metrics
    port: http-web
  - path: /metrics
    port: reloader-web
  namespaceSelector:
    matchNames:
    - sentinel
  selector:
    matchLabels:
      app.kubernetes.io/instance: sentinel-stack
      app: sentinel-prometheus
      release: prometheus
