# nameOverride: "sentinel"
# fullnameOverride: "sentinel"

commonLabels:
  stack: sentinel

crds:
  enabled: false

defaultRules:
  create: false

global:
  rbac:
    create: false

windowsMonitoring:
  enabled: false

prometheus-windows-exporter:
  prometheus:
    monitor:
      enabled: false

alertmanager:
  enabled: false

grafana:
  enabled: false
 
kubernetesServiceMonitors:
  enabled: false

kubeApiServer:
  enabled: false

kubelet:
  enabled: false

kubeControllerManager:
  enabled: false

coreDns:
  enabled: false
  
kubeDns:
  enabled: false

kubeEtcd:
  enabled: false

kubeScheduler:
  enabled: false

kubeProxy:
  enabled: false

kubeStateMetrics:
  enabled: false

nodeExporter:
  enabled: false

prometheusOperator:
  enabled: false

prometheus:
  enabled: false

thanosRuler:
  enabled: false

cleanPrometheusOperatorObjectNames: false
