apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: argocd
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: alloy

  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: alloy
      targetRevision: 1.12.1
      helm:
        releaseName: alloy
        valueFiles:
          - $values/tools/alloy/values.yaml

    - repoURL: https://github.com/ViniciusPilan/k8s-cluster.git
      targetRevision: observability
      ref: values

  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
      - CreateNamespace=true
