apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager

  sources:
  - repoURL: quay.io/jetstack/charts
    chart: cert-manager
    targetRevision: v1.21.2
    helm:
      releaseName: cert-manager
      valueFiles:
        - $values/tools/certmanager/values.yaml

  - repoURL: https://github.com/ViniciusPilan/k8s-cluster.git
    targetRevision: refactor-v1
    ref: values

  - repoURL: https://github.com/ViniciusPilan/k8s-cluster.git
    targetRevision: refactor-v1
    path: tools/certmanager/manifests

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
