apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  namespace: argocd
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system

  sources:
    - repoURL: https://istio-release.storage.googleapis.com/charts
      chart: base
      targetRevision: 1.27.1
      helm:
        releaseName: istio-base
        # valueFiles:
        #   - $values/tools/istio/base/values.yaml

    # - repoURL: https://github.com/ViniciusPilan/k8s-cluster.git
    #   targetRevision: main
    #   ref: values

  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true

    syncOptions:
      - CreateNamespace=true
