apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system

  sources:
    # Istio CNI
    - repoURL: https://istio-release.storage.googleapis.com/charts
      chart: cni
      targetRevision: 1.30.1
      helm:
        releaseName: istio-cni
        valueFiles:
          - $values/tools/istio/cni/values.yaml

    # Istiod
    - repoURL: https://istio-release.storage.googleapis.com/charts
      chart: istiod
      targetRevision: 1.30.1
      helm:
        releaseName: istiod
        valueFiles:
          - $values/tools/istio/istiod/values.yaml

    # Istio gateway
    - repoURL: https://istio-release.storage.googleapis.com/charts
      chart: gateway
      targetRevision: 1.30.1
      helm:
        releaseName: istio-ingress
        valueFiles:
          - $values/tools/istio/gateway/values.yaml

    - repoURL: https://github.com/ViniciusPilan/k8s-cluster.git
      targetRevision: refactor-v1
      ref: values

  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true