# Ref: https://github.com/grafana/mimir/blob/main/operations/helm/charts/mimir-distributed/values.yaml

minio:
  enabled: false

global:
  extraEnvFrom:
    - secretRef:
        name: mimir-metrics-bucket-access

mimir:
  structuredConfig:
    common:
      storage:
        backend: s3
        s3:
          bucket_name: "${BUCKET_NAME}"
          endpoint: "${BUCKET_HOST}:${BUCKET_PORT}"
          access_key_id: "${AWS_ACCESS_KEY_ID}" # This is a secret injected via an environment variable
          secret_access_key: "${AWS_SECRET_ACCESS_KEY}" # This is a secret injected via an environment variable
          http:
            insecure_skip_verify: true

ruler:
  enabled: false

alertmanager:
  enabled: false
