[tools]
tools-server ansible_host=192.168.12.29 ansible_user=ubuntu

[kubernetes_control_plane]
homelab-k8s-controlplane01 ansible_host=192.168.12.21 ansible_user=ubuntu

[kubernetes_workers]
homelab-k8s-worker01 ansible_host=192.168.12.22 ansible_user=ubuntu
