apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications
  namespace: argocd
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  sources:
    - repoURL: https://github.com/ViniciusPilan/k8s-cluster.git
      targetRevision: refactor-v1
      path: tools/argo/applications

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
