apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    grafana_datasource: "1"
  name: grafana-alertmanager-datasource
  namespace: metrics
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: "Alertmanager"
      type: alertmanager
      uid: alertmanager
      url: http://prometheus-alertmanager.metrics:9093/
      access: proxy
      jsonData:
        handleGrafanaManagedAlerts: false
        implementation: prometheus

