apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trace-stack
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://github.com/ViniciusPilan/k8s-cluster.git
    targetRevision: echo-api
    ref: values
  ###################### Prometheus ######################
  - repoURL: https://jaegertracing.github.io/helm-charts
    chart: jaeger-operator
    targetRevision: 2.56.0
    helm:
      releaseName: jaeger
      valueFiles:
      - $values/cluster/envs/dev/apps/jaeger/base.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: trace
  syncPolicy:
    syncOptions:
    - CreateNamespace=true