apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: grafana
    prometheus: sentinel
  name: grafana
  namespace: sentinel
spec:
  endpoints:
  - honorLabels: true
    path: /metrics
    port: http-web
    scheme: http
    scrapeTimeout: 30s
  jobLabel: grafana
  namespaceSelector:
    matchNames:
    - sentinel
  selector:
    matchLabels:
      app.kubernetes.io/instance: sentinel-stack
      app.kubernetes.io/name: grafana
