apiVersion: v1
kind: Pod
metadata:
  labels:
    run: echo-api
  name: echo-api
spec:
  containers:
  - image: echo-api:dev
    name: echo-api
    ports:
    - containerPort: 8080
  restartPolicy: Always
