apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: echo-api
  namespace: default
spec:
  endpoints:
  - path: /metrics
    port: app
  selector:
    matchLabels:
      app: echo-api
