apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: echo-api
  namespace: metrics
spec:
  endpoints:
  - path: /metrics
    port: app
  namespaceSelector:
    matchNames:
    - metrics
  selector:
    matchLabels:
      app: echo-api
