# Full chart values for Grafana version 13.2.6: https://github.com/grafana-community/helm-charts/blob/grafana-13.2.6/charts/grafana/values.yaml

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Mimir
        type: prometheus
        access: proxy
        url: http://mimir-gateway.mimir.svc.cluster.local/prometheus
        isDefault: true
        jsonData:
          httpHeaderName1: X-Scope-OrgID
        secureJsonData:
          httpHeaderValue1: anonymous
